# nvidia-docker-toolkit
# cuda のバージョンを指定
FROM nvidia/cuda:11.7.1-base-ubuntu22.04

# 必要なパッケージのインストール
RUN apt-get update && apt-get install -y \
    python3-pip \
    sudo \
    wget \
    git \
    vim

# python3 を python コマンドで実行できるように設定
RUN ln -s /usr/bin/python3.10 /usr/bin/python
RUN pip install --upgrade pip

# cuda に対応する pytrch をインストール

RUN pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
RUN pip install jupyterlab
RUN pip install seaborn scikit-learn
WORKDIR /work
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--LabApp.token=''"]